/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.LinksTrackings;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksTrackingsRecord extends UpdatableRecordImpl<LinksTrackingsRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LINKS_TRACKINGS.TG_CHAT_ID</code>.
     */
    public void setTgChatId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>LINKS_TRACKINGS.TG_CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getTgChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>LINKS_TRACKINGS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>LINKS_TRACKINGS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return LinksTrackings.LINKS_TRACKINGS.TG_CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return LinksTrackings.LINKS_TRACKINGS.LINK_ID;
    }

    @Override
    @NotNull
    public Long component1() {
        return getTgChatId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public Long value1() {
        return getTgChatId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public LinksTrackingsRecord value1(@NotNull Long value) {
        setTgChatId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksTrackingsRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public LinksTrackingsRecord values(@NotNull Long value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LinksTrackingsRecord
     */
    public LinksTrackingsRecord() {
        super(LinksTrackings.LINKS_TRACKINGS);
    }

    /**
     * Create a detached, initialised LinksTrackingsRecord
     */
    @ConstructorProperties({ "tgChatId", "linkId" })
    public LinksTrackingsRecord(@NotNull Long tgChatId, @NotNull Long linkId) {
        super(LinksTrackings.LINKS_TRACKINGS);

        setTgChatId(tgChatId);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LinksTrackingsRecord
     */
    public LinksTrackingsRecord(edu.java.domain.jooq.tables.pojos.LinksTrackings value) {
        super(LinksTrackings.LINKS_TRACKINGS);

        if (value != null) {
            setTgChatId(value.getTgChatId());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
