app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 100s
    force-check-delay: 10s
  git-hub-client-retry:
    max-attempts: 3
    duration: 2s
    strategy: exponential
    status-codes:
      - 500
      - 502
      - 503
  stack-overflow-client-retry:
    max-attempts: 3
    duration: 2s
    strategy: exponential
    status-codes:
      - 500
      - 502
      - 503
  bot-client-retry:
    max-attempts: 3
    duration: 2s
    strategy: exponential
    status-codes:
      - 500
      - 502
      - 503
  kafka-updates-producer:
    topic-name: link_updates
    bootstrap-servers: localhost:29092
    acks-mode: 1
    delivery-timeout: 60s
    linger-ms: 12_000
    batch-size: 100_000
    max-in-flight-per-connection: 5
    enable-idempotence: true
  use-queue: true

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

# Конфигурация Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - info
          - health
          - prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
