app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
  bot-name: "ISH_web_scraper_bot"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

# Конфигурация Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
