app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
  bot-name: "ISH_web_scraper_bot"
  scrapper-client-retry:
    max-attempts: 3
    duration: 2s
    strategy: exponential
    status-codes:
      - 500
      - 502
      - 503
  kafka-updates-consumer-config:
    topic-name: link_updates
    bootstrap-servers: localhost:29092
    group-id: bot
    auto-offset-reset: earliest
    concurrency: 1
  kafka-dlq-producer-config:
    topic-name: link_updates_dlq
    bootstrap-servers: localhost:29092
    linger-ms: 100

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

# Конфигурация Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

# Конфигурация Rate limiting
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\":
      \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 50
              refill-capacity: 1
              time: 2
              unit: seconds
              initial-capacity: 10
              refill-speed: interval
