app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
  bot-name: "ISH_web_scraper_bot"
  scrapper-client-retry:
    max-attempts: 3
    duration: 2s
    strategy: exponential
    status-codes:
      - 500
      - 502
      - 503

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

# Конфигурация Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
