/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables;


import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.records.LinksTrackingsRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinksTrackings extends TableImpl<LinksTrackingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINKS_TRACKINGS</code>
     */
    public static final LinksTrackings LINKS_TRACKINGS = new LinksTrackings();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinksTrackingsRecord> getRecordType() {
        return LinksTrackingsRecord.class;
    }

    /**
     * The column <code>LINKS_TRACKINGS.TG_CHAT_ID</code>.
     */
    public final TableField<LinksTrackingsRecord, Long> TG_CHAT_ID = createField(DSL.name("TG_CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINKS_TRACKINGS.LINK_ID</code>.
     */
    public final TableField<LinksTrackingsRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private LinksTrackings(Name alias, Table<LinksTrackingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinksTrackings(Name alias, Table<LinksTrackingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINKS_TRACKINGS</code> table reference
     */
    public LinksTrackings(String alias) {
        this(DSL.name(alias), LINKS_TRACKINGS);
    }

    /**
     * Create an aliased <code>LINKS_TRACKINGS</code> table reference
     */
    public LinksTrackings(Name alias) {
        this(alias, LINKS_TRACKINGS);
    }

    /**
     * Create a <code>LINKS_TRACKINGS</code> table reference
     */
    public LinksTrackings() {
        this(DSL.name("LINKS_TRACKINGS"), null);
    }

    public <O extends Record> LinksTrackings(Table<O> child, ForeignKey<O, LinksTrackingsRecord> key) {
        super(child, key, LINKS_TRACKINGS);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<LinksTrackingsRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C16;
    }

    @Override
    @NotNull
    public List<ForeignKey<LinksTrackingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_C, Keys.CONSTRAINT_C1);
    }

    private transient TgChats _tgChats;
    private transient Links _links;

    /**
     * Get the implicit join path to the <code>PUBLIC.TG_CHATS</code> table.
     */
    public TgChats tgChats() {
        if (_tgChats == null)
            _tgChats = new TgChats(this, Keys.CONSTRAINT_C);

        return _tgChats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null)
            _links = new Links(this, Keys.CONSTRAINT_C1);

        return _links;
    }

    @Override
    @NotNull
    public LinksTrackings as(String alias) {
        return new LinksTrackings(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinksTrackings as(Name alias) {
        return new LinksTrackings(alias, this);
    }

    @Override
    @NotNull
    public LinksTrackings as(Table<?> alias) {
        return new LinksTrackings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksTrackings rename(String name) {
        return new LinksTrackings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksTrackings rename(Name name) {
        return new LinksTrackings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinksTrackings rename(Table<?> name) {
        return new LinksTrackings(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
