/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.LinksTrackings;
import edu.java.domain.jooq.tables.TgChats;
import edu.java.domain.jooq.tables.records.LinksRecord;
import edu.java.domain.jooq.tables.records.LinksTrackingsRecord;
import edu.java.domain.jooq.tables.records.TgChatsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URL }, true);
    public static final UniqueKey<LinksTrackingsRecord> CONSTRAINT_C16 = Internal.createUniqueKey(LinksTrackings.LINKS_TRACKINGS, DSL.name("CONSTRAINT_C16"), new TableField[] { LinksTrackings.LINKS_TRACKINGS.TG_CHAT_ID, LinksTrackings.LINKS_TRACKINGS.LINK_ID }, true);
    public static final UniqueKey<TgChatsRecord> CONSTRAINT_6 = Internal.createUniqueKey(TgChats.TG_CHATS, DSL.name("CONSTRAINT_6"), new TableField[] { TgChats.TG_CHATS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinksTrackingsRecord, TgChatsRecord> CONSTRAINT_C = Internal.createForeignKey(LinksTrackings.LINKS_TRACKINGS, DSL.name("CONSTRAINT_C"), new TableField[] { LinksTrackings.LINKS_TRACKINGS.TG_CHAT_ID }, Keys.CONSTRAINT_6, new TableField[] { TgChats.TG_CHATS.ID }, true);
    public static final ForeignKey<LinksTrackingsRecord, LinksRecord> CONSTRAINT_C1 = Internal.createForeignKey(LinksTrackings.LINKS_TRACKINGS, DSL.name("CONSTRAINT_C1"), new TableField[] { LinksTrackings.LINKS_TRACKINGS.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
}
