/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq;


import edu.java.domain.jooq.tables.Links;
import edu.java.domain.jooq.tables.LinksTrackings;
import edu.java.domain.jooq.tables.TgChats;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>LINKS</code>.
     */
    public static final Links LINKS = Links.LINKS;

    /**
     * The table <code>LINKS_TRACKINGS</code>.
     */
    public static final LinksTrackings LINKS_TRACKINGS = LinksTrackings.LINKS_TRACKINGS;

    /**
     * The table <code>TG_CHATS</code>.
     */
    public static final TgChats TG_CHATS = TgChats.TG_CHATS;
}
